version: "3.9"
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: next-job
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  next-job-app:
    image: next-job
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - postgres-data:/app/postgres-data
      - ./:/app
      - ./public/uploads:/app/public/uploads
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/next-job?schema=public&connect_timeout=60
    ports:
      - 3000:3000
volumes:
  postgres-data:
